#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Edit the below values, the only required change is DOMAIN_NAME
# These values are _ONLY_ used at install time.