#!/usr/bin/python

import os

#datadir = os.path.dirname(os.path.abspath(__file__)) + '/wsgi'
datadir = os.environ['DOCUMENT_ROOT']
here = os.path.join(datadir, '..')
#here = datadir

def application(environ, start_response):

    status = '200 OK'
    headers = [('Content-type', 'text/plain')]

    start_response(status, headers)

    ret = ["%s: %s\n" % (key, value)
           for key, value in environ.iteritems()]
    return ret


if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    httpd = make_server('localhost', 8051, application)
    # Wait for a single request, serve it and quit.
    httpd.serve_forever()
